version: '3.8'

services:
  ubuntu:
    image: cloudwave:buildexample.1
    build:
      context: ../buildproject
      dockerfile: "Dockerfile"
    entrypoint: /bin/bash
    command:
      - -c
      - "sleep 3600"
    restart: no
