#docker-compose.yaml
version: "3.8"

services:
    ubuntu:
        image: ubuntu:22.04
        tty: true
        stdin_open: true
        restart: no #재시작 x

    ubuntu2:
        image: ubuntu:22.04
        entrypoint: /bin/bash
        command:
            - -c
            - sleep infinity
        restart: no
