version: '3.8'
name: 'cloudwave'

services:
  success:
    image: ubuntu:22.04
    entrypoint: /bin/bash
    command:
      - -c
      - sleep infinity
    networks:
      private: {}

  fail:
    image: ubuntu:22.04
    entrypoint: /bin/bash
    command:
      - -c
      - sleep fail
    networks:
      private: {}

networks:
  private: