version: '3.8'

services:
  ubuntu:
    image: cloudwave:example.1
    build:
      dockerfile: "Dockerfile"
    entrypoint: /bin/bash
    command:
      - -c
      - "sleep 3600"
    restart: no

  nginx:
    image: nginx:latest
    ports:
      - "8090:8090"
    restart: always